/* recognizeExp.c, Gerard Renardel, 29 January 2014
 *
 * In this file a recognizer acceptExpression is definined that can recognize 
 * arithmetical expressions generated by the following BNF grammar:
 *
 * <expression>  ::= <term> { '+'  <term> | '-' <term> }
 * 
 * <term>       ::= <factor> { '*' <factor> | '/' <factor> }
 *
 * <factor>     ::= <number> | <identifier> | '(' <expression> ')'
 *
 * Input for the recognizer is the token list constructed by the scanner (in scanner.c). 
 * For the recognition of a token list the method of *recursive descent* is used. 
 * It relies on the use of three functions for the recognition and processing of
 * terms, factors and expressions, respectively. 
 * These three functions are defined with mutual recursion, corresponding with the 
 * structure of the BNF grammar.
 */

/* The grammar implemented after the modification
 * <equation>   ::= <expression> '=' <expression>
 *
 * <expression> ::= <term> { '+'  <term> | '-' <term> }
 *                | '-' <term> { '+'  <term> | '-' <term> }
 *
 * <term>       ::= <natnum> | <natnum> <identifier> | <natnum> <identifier> '^' <natnum>
*/

#include <stdio.h>  /* getchar, printf */
#include <stdlib.h> /* NULL */
#include "scanner.h"
#include "recognizeEq.h"
#include <assert.h>

const int TRUE = 1;
const int FALSE = 0;

/* The functions acceptNumber, acceptIdentifier and acceptCharacter have as
 * (first) argument a pointer to an token list; moreover acceptCharacter has as
 * second argument a character. They check whether the first token
 * in the list is a number, an identifier or the given character, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptNumber(List *lp) {
  // fprintf(stderr, "acceptNumber\n");
  if (*lp != NULL && (*lp)->tt == Number) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptIdentifier(List *lp) {
  // fprintf(stderr, "acceptIdentifier\n");
  if (*lp != NULL && (*lp)->tt == Identifier ) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptCharacter(List *lp, char c) {
  // fprintf(stderr, "acceptChar: %c\n", c);
  if (*lp != NULL && (*lp)->tt == Symbol && ((*lp)->t).symbol == c ) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

/* The functions acceptFactor, acceptTerm and acceptExpression have as
 * argument a pointer to a token list. They check whether the token list
 * has an initial segment that can be recognized as factor, term or expression, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptTerm(List *lp) {
  // fprintf(stderr, "acceptTerm\n");
  if ( !acceptNumber(lp) ) {
    return FALSE;
  }
  if( acceptIdentifier(lp)){
    if( acceptCharacter(lp, '^') ){
      if( acceptNumber(lp) ){
        return TRUE;
      }
      return FALSE;
    }
    return TRUE;
  }
  return TRUE;
}

int acceptExpression(List *lp) {
  // fprintf(stderr, "acceptExpression\n");
  if ( !( acceptTerm(lp) || (acceptCharacter(lp, '-') && acceptTerm(lp)) ) ) {
    return FALSE;
  }
  while ( acceptCharacter(lp,'+') || acceptCharacter(lp,'-') ) {
    if ( !acceptTerm(lp) ) {
      return FALSE;
    }
  } /* no + or -, so we reached the end of the expression */
  return TRUE;
}

int acceptEquation(List *lp){
  if(!acceptExpression(lp)){
    return FALSE;
  }
  if(!acceptCharacter(lp, '=')){
    return FALSE;
  }
  if(!acceptExpression(lp)){
    return FALSE;
  }
  return TRUE;
}

int isEqual(char *ar1, char*ar2, int size){
  int i;
  for(i=0; i<size; i++){
    if (ar1[i] == '\0' && ar2[i] == '\0') {
      return TRUE;
    }
    if(ar1[i] != ar2[i]){
      return FALSE;
    }
  }
  return TRUE;
}

int isOneVar(List *lp){
  int varFound = FALSE;
  char *var = NULL;
  while(*lp != NULL){
    if((*lp)->tt == Identifier){
      if(var == NULL){
        varFound = TRUE;
        var = (*lp)->t.identifier;
      }else{
        if(!isEqual(var, (*lp)->t.identifier, MAXIDENT*10) ){
          return FALSE;
        }
      }
    }
    *lp = (*lp)->next;
  }
  return varFound;
}
/* The next function can be used to demonstrate the recognizer.
 */

int max(int a, int b){
  return (a > b) ? a : b;
}

int degree(List *lp){
  int degree = -100;
  while(*lp != NULL){
    if( acceptIdentifier(lp) ){
      if( *lp != NULL && acceptCharacter(lp, '^') ){
        degree = max(degree, (*lp)->t.number);
      }else{
        degree = max(degree, 1);
      }
    }
    if(*lp != NULL){
      *lp = (*lp)->next;
    }
  }
  return degree;
}

void recognizeEquations() {
  char *ar;
  List tl, tl1;
  printf("give an equation: ");
  ar = readInput();
  while (ar[0] != '!') {
    tl = tokenList(ar);
    printList(tl);
    tl1 = tl;
    if ( acceptEquation(&tl1) && tl1 == NULL ) {
      tl1 = tl;
      printf("this is an equation");
      if(isOneVar(&tl1)) {
        tl1 = tl;
        printf(" in 1 variable of degree %d\n", degree(&tl1));
      } else {
        printf(", but not in 1 variable\n");
      }
    } else {
      printf("this is not an equation\n");
    }
    free(ar);
    freeTokenList(tl);
    printf("\ngive an equation: ");
    ar = readInput();
  }
  free(ar);
  printf("good bye\n");
}

